#!/usr/bin/env python3
"""Show all patches generated by ATLAS agents."""

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from dotenv import load_dotenv
load_dotenv(Path(__file__).parent.parent / ".env")

from atlas.core.config import Config
from atlas.agents.gemini_client import GeminiClient
from atlas.agents.prompt_styles import PromptStyleName, get_style_by_name, BASE_SYSTEM_PROMPT


BUGGY_CODE = '''
def calculate_average(numbers):
    """Calculate the average of a list of numbers."""
    total = 0
    for num in numbers:
        total += num
    return total / len(numbers)


def get_user_display_name(user):
    """Get the display name for a user."""
    return user["first_name"] + " " + user["last_name"]


def find_item_by_id(items, target_id):
    """Find an item in a list by its ID."""
    for item in items:
        if item["id"] == target_id:
            return item
    # Bug: returns None implicitly
'''

ISSUE = """Fix: 1) calculate_average crashes on empty list, 2) get_user_display_name crashes on missing keys, 3) find_item_by_id returns None silently"""


async def generate_patch(client, style_name):
    style = get_style_by_name(style_name)
    prompt = f"""{style.get_system_prompt(BASE_SYSTEM_PROMPT)}

## Code (utils.py)
```python
{BUGGY_CODE}
```

## Issue
{ISSUE}

Output ONLY a unified diff patch:
```diff
--- a/utils.py
+++ b/utils.py
...
```"""

    result = await client.generate(prompt=prompt, max_tokens=2000, temperature=0.7 + style.temperature_offset)
    return result.text


async def main():
    config = Config.from_env()
    client = GeminiClient(config)

    styles = [
        ("AGENT 0 - MINIMAL_DIFF", PromptStyleName.MINIMAL_DIFF, "Makes smallest possible change"),
        ("AGENT 1 - VERBOSE_EXPLAINER", PromptStyleName.VERBOSE_EXPLAINER, "Thinks step-by-step"),
        ("AGENT 2 - REFACTOR_FIRST", PromptStyleName.REFACTOR_FIRST, "Cleans up then fixes"),
        ("AGENT 3 - DEBUGGER", PromptStyleName.DEBUGGER, "Traces execution flow"),
        ("AGENT 4 - REPO_ONLY", PromptStyleName.REPO_ONLY, "Follows existing patterns"),
    ]

    print("=" * 80)
    print(" ATLAS: 5 AI AGENTS SOLVING THE SAME BUG")
    print("=" * 80)
    print("\nBUGGY CODE:")
    print(BUGGY_CODE)
    print("\nISSUE:", ISSUE)
    print("\n" + "=" * 80)

    for name, style, desc in styles:
        print(f"\n{'='*80}")
        print(f" {name}")
        print(f" Strategy: {desc}")
        print("=" * 80)

        patch = await generate_patch(client, style)
        print(patch)

    print("\n" + "=" * 80)
    print(" ALL 5 AGENTS COMPLETE - ATLAS would now cluster & score these patches")
    print("=" * 80)


if __name__ == "__main__":
    asyncio.run(main())
